[package]
name = "sqlx"
version = "0.9.0"
edition.workspace = true
license.workspace = true
description = "Euterpe SQLite-only facade for SQLx 0.9"
publish = false

[features]
default = []
derive = []
macros = []
migrate = ["sqlx-core/migrate"]
sqlite = ["sqlx-sqlite/bundled", "sqlx-sqlite/deserialize", "sqlx-sqlite/unlock-notify"]
sqlite-bundled = ["sqlx-sqlite/bundled"]
sqlite-deserialize = ["sqlx-sqlite/deserialize"]
sqlite-load-extension = ["sqlx-sqlite/load-extension"]
sqlite-unbundled = ["sqlx-sqlite/unbundled"]
sqlite-unlock-notify = ["sqlx-sqlite/unlock-notify"]
runtime-tokio = ["sqlx-core/_rt-tokio"]
runtime-async-std = ["sqlx-core/_rt-async-std"]
runtime-async-global-executor = ["sqlx-core/_rt-async-global-executor"]
runtime-smol = ["sqlx-core/_rt-smol"]
tls-none = []
tls-native-tls = ["sqlx-core/_tls-native-tls"]
tls-rustls = ["tls-rustls-ring"]
tls-rustls-aws-lc-rs = ["sqlx-core/_tls-rustls-aws-lc-rs"]
tls-rustls-ring = ["tls-rustls-ring-webpki"]
tls-rustls-ring-native-roots = ["sqlx-core/_tls-rustls-ring-native-roots"]
tls-rustls-ring-webpki = ["sqlx-core/_tls-rustls-ring-webpki"]
mysql = []
postgres = []
any = ["sqlx-core/any"]
json = ["sqlx-core/json", "sqlx-sqlite/json"]
chrono = ["sqlx-core/chrono", "sqlx-sqlite/chrono"]
uuid = ["sqlx-core/uuid", "sqlx-sqlite/uuid"]
time = ["sqlx-core/time", "sqlx-sqlite/time"]

[dependencies]
sqlx-core = { version = "=0.9.0", default-features = false }
sqlx-sqlite = { version = "=0.9.0", default-features = false }
