/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OpenAPI document (JSON) */
        get: operations["getOpenApiSpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/server/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server configuration snapshot (no secrets) */
        get: operations["getServerInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qobuz/sync/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Most recent favorites sync run */
        get: operations["getQobuzSyncLatest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qobuz/oauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Start Qobuz OAuth (browser redirect URL)
         * @description Returns the Qobuz sign-in URL and a CSRF `state` stored server-side.
         *     Credentials are only stored via OAuth callback into `qobuz_accounts` (not env).
         */
        get: operations["qobuzOAuthStart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qobuz/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OAuth callback (Qobuz redirects here)
         * @description Exchanges `code` for UAT, upserts `qobuz_accounts`, sets active account, reloads client. Redirects to SPA settings.
         */
        get: operations["qobuzOAuthCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qobuz/connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Qobuz connection status (no secrets) */
        get: operations["getQobuzConnection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qobuz/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disconnect active Qobuz account
         * @description Deletes the active account row, clears `qobuz.active_account_id`, reloads API client.
         */
        post: operations["qobuzLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qobuz/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List linked Qobuz accounts (no UAT) */
        get: operations["listQobuzAccounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qobuz/test-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Qobuz session token (debug only; does not persist) */
        post: operations["qobuzTestLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qobuz/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync favorite albums from Qobuz into local database */
        post: operations["qobuzSync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/qobuz/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List synced favorite albums */
        get: operations["listQobuzFavorites"];
        put?: never;
        /** Add albums to Qobuz favorites */
        post: operations["addQobuzFavorites"];
        /** Remove albums from Qobuz favorites */
        delete: operations["removeQobuzFavorites"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/downloads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List download jobs */
        get: operations["listDownloads"];
        put?: never;
        /** Queue a download job */
        post: operations["createDownload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/downloads/by-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue album download from play.qobuz.com URL or album ref */
        post: operations["createDownloadByUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/downloads/purge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete all finished download jobs (completed, failed, cancelled) */
        post: operations["purgeFinishedDownloads"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/downloads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get download job by id */
        get: operations["getDownload"];
        put?: never;
        post?: never;
        /**
         * Cancel a queued/running job, or permanently delete a finished job
         * @description Without `purge`: cancel a `queued` or `running` job (sets status to `cancelled`).
         *     With `purge=1`: permanently remove the row; only allowed for `completed`, `failed`, or `cancelled`.
         */
        delete: operations["cancelDownload"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start background library filesystem scan */
        post: operations["startLibraryScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/scan/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest library scan run */
        get: operations["getLibraryScanLatest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/scan/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Library scan run by id */
        get: operations["getLibraryScan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List indexed local albums */
        get: operations["listLibraryAlbums"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/albums/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Album detail with tracks */
        get: operations["getLibraryAlbum"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/albums/{id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Album cover image file from library disk
         * @description Serves the file at `albums.cover_path` under the configured library root.
         *     Returns 404 if the album has no `cover_path` or the file is missing.
         */
        get: operations["getLibraryAlbumCover"];
        /**
         * Upload or replace album cover image
         * @description Writes `cover.<ext>` under the album directory (from `albums.path`), updates
         *     `albums.cover_path`, and embeds the image in all audio files of the album.
         *     Maximum body size 20 MiB. Supported types JPEG, PNG, WebP, BMP.
         */
        put: operations["putLibraryAlbumCover"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/tracks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Track detail */
        get: operations["getLibraryTrack"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update audio file tags (writes to disk) */
        patch: operations["patchLibraryTrackTags"];
        trace?: never;
    };
    "/api/v1/library/albums/{id}/metadata/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search external catalog for album metadata candidates */
        post: operations["albumMetadataLookup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/library/albums/{id}/metadata/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply selected metadata candidate to album files and index */
        post: operations["albumMetadataApply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configured integrations */
        get: operations["listIntegrations"];
        put?: never;
        /** Add integration from catalog */
        post: operations["createIntegration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Available integration providers */
        get: operations["integrationsCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove integration */
        delete: operations["deleteIntegration"];
        options?: never;
        head?: never;
        /** Update integration */
        patch: operations["patchIntegration"];
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server-sent events stream (job and scan progress) */
        get: operations["subscribeEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            version: string;
        };
        ErrorBody: {
            code: string;
            message: string;
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        QobuzTestLoginRequest: {
            /** Format: int64 */
            user_id: number;
            auth_token: string;
        };
        QobuzOAuthStartResponse: {
            /** Format: uri */
            authorize_url: string;
            state: string;
        };
        QobuzConnectionStatusResponse: {
            connected: boolean;
            /** Format: int64 */
            active_account_id?: number;
            /** Format: int64 */
            qobuz_user_id?: number;
            display_name?: string;
            membership_label?: string;
            master_key_configured: boolean;
        };
        QobuzAccountListItem: {
            /** Format: int64 */
            id: number;
            label?: string;
            /** Format: int64 */
            qobuz_user_id: number;
            display_name?: string;
            membership_label?: string;
            uat_obtained_at: string;
            is_active: boolean;
        };
        QobuzAccountsListResponse: {
            items: components["schemas"]["QobuzAccountListItem"][];
        };
        QobuzTestLoginResponse: {
            membership: string;
            user_auth_token_refreshed: boolean;
        };
        QobuzSyncResponse: {
            /** Format: int64 */
            run_id: number;
            albums_total: number;
            added: number;
            removed: number;
        };
        ServerInfoResponse: {
            version: string;
            library_path: string;
            credentials_configured: boolean;
            admin_auth_required: boolean;
        };
        QobuzSyncRunSummary: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            status: "running" | "success" | "failed";
            started_at: string;
            finished_at?: string | null;
            albums_total?: number;
            albums_added?: number;
            albums_removed?: number;
            error_message?: string | null;
        };
        QobuzSyncLatestResponse: {
            run: components["schemas"]["QobuzSyncRunSummary"] | null;
        };
        QobuzFavoriteItem: {
            /** @description Qobuz `album/get` id (short ref or slug). Use as `album_api_id` in POST /downloads. */
            album_api_id: string;
            /** Format: int64 */
            qobuz_id: number;
            title: string;
            artist_name: string;
            /** @default false */
            in_library: boolean;
            /** Format: int64 */
            local_album_id?: number | null;
            /** @description Qobuz thumbnail URL from last sync (when not in library) */
            cover_url?: string | null;
        };
        QobuzFavoritesListResponse: {
            items: components["schemas"]["QobuzFavoriteItem"][];
            next_cursor?: string | null;
            has_more: boolean;
        };
        QobuzFavoritesMutateRequest: {
            album_ids: number[];
        };
        CreateDownloadByUrlRequest: {
            /** @description play.qobuz.com album URL, www.qobuz.com album link, or bare album/get ref */
            url: string;
            /** @description Qobuz format_id (5=MP3, 6=FLAC 16/44, 7=FLAC 24, 27=Hi-Res) */
            quality: number;
        };
        /** @enum {string} */
        DownloadJobStatus: "queued" | "running" | "completed" | "failed" | "cancelled";
        /** @enum {string} */
        DownloadJobType: "album" | "track" | "artist" | "playlist";
        CreateDownloadRequest: {
            job_type: components["schemas"]["DownloadJobType"];
            /** @description Qobuz `album/get` id (short ref e.g. zg7pv28g4mldg). From GET /api/v1/qobuz/favorites. */
            album_api_id: string;
            /**
             * @description Qobuz format_id (5=MP3, 6=FLAC, 7=Hi-Res, 27=Hi-Res+)
             * @enum {integer}
             */
            quality: 5 | 6 | 7 | 27;
            /**
             * Format: int64
             * @description Optional catalog id for dedup and job display.
             */
            qobuz_id?: number;
        };
        CreateDownloadResponse: {
            /** Format: int64 */
            job_id: number;
        };
        DownloadJob: {
            /** Format: int64 */
            id: number;
            status: components["schemas"]["DownloadJobStatus"];
            job_type: components["schemas"]["DownloadJobType"];
            /** Format: int64 */
            qobuz_id: number;
            quality: number;
            progress_pct: number;
            error_message?: string | null;
            created_at: string;
            updated_at: string;
        };
        DownloadJobListResponse: {
            items: components["schemas"]["DownloadJob"][];
            next_cursor?: string | null;
            has_more: boolean;
        };
        DownloadPurgeResponse: {
            /** Format: int64 */
            deleted: number;
        };
        JobProgressEvent: {
            /** Format: int64 */
            id: number;
            progress_pct: number;
        };
        LibraryScanStartResponse: {
            /** Format: int64 */
            scan_id: number;
        };
        LibraryScanRunSummary: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            status: "running" | "success" | "failed" | "cancelled";
            files_seen: number;
            files_indexed: number;
            started_at: string;
            finished_at?: string | null;
            error_message?: string | null;
        };
        LibraryScanLatestResponse: {
            run: components["schemas"]["LibraryScanRunSummary"] | null;
        };
        ScanProgressEvent: {
            /** Format: int64 */
            scan_id: number;
            files_seen: number;
            files_indexed: number;
        };
        LibraryAlbumItem: {
            /** Format: int64 */
            id: number;
            title: string;
            artist_name: string;
            year?: number | null;
            track_count: number;
            cover_path?: string | null;
        };
        LibraryAlbumListResponse: {
            items: components["schemas"]["LibraryAlbumItem"][];
            next_cursor?: string | null;
            has_more: boolean;
        };
        LibraryTrackItem: {
            /** Format: int64 */
            id: number;
            title: string;
            track_number?: number | null;
            year?: number | null;
            disc_number?: number | null;
            genre?: string | null;
            path: string;
            duration_sec?: number | null;
        };
        LibraryAlbumDetailResponse: {
            /** Format: int64 */
            id: number;
            title: string;
            artist_name: string;
            year?: number | null;
            cover_path?: string | null;
            tracks: components["schemas"]["LibraryTrackItem"][];
        };
        LibraryTrackDetailResponse: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            album_id: number;
            title: string;
            artist_name: string;
            album_title: string;
            track_number?: number | null;
            year?: number | null;
            disc_number?: number | null;
            genre?: string | null;
            path: string;
            duration_sec?: number | null;
        };
        AlbumCoverUploadResponse: {
            /** @description Library-relative path to the cover file */
            cover_path: string;
            /** @description Number of track files that received embedded cover art */
            tracks_embedded: number;
        };
        LibraryTrackTagsPatchRequest: {
            title?: string;
            artist_name?: string;
            album_title?: string;
            track_number?: number;
            year?: number;
            disc_number?: number;
            genre?: string;
        };
        MetadataCandidate: {
            id: string;
            title: string;
            artist_name: string;
            year?: number | null;
            /** Format: float */
            score: number;
            track_count?: number | null;
            source_label: string;
        };
        AlbumMetadataLookupRequest: {
            /** Format: int64 */
            integration_id: number;
            /**
             * @description Catalog page (Discogs supports pagination; other providers use page 1 only).
             * @default 1
             */
            page: number;
        };
        AlbumMetadataLookupResponse: {
            candidates: components["schemas"]["MetadataCandidate"][];
            page: number;
            /** @description True when more catalog pages are available (Discogs). */
            has_more: boolean;
        };
        AlbumMetadataApplyRequest: {
            /** Format: int64 */
            integration_id: number;
            candidate_id: string;
        };
        AlbumMetadataApplyResponse: {
            tracks_updated: number;
            cover_applied: boolean;
            warnings: string[];
        };
        IntegrationConfigFieldSchema: {
            key: string;
            label: string;
            field_type: string;
            required: boolean;
            secret: boolean;
            placeholder?: string | null;
        };
        IntegrationCatalogEntry: {
            provider: string;
            integration_type: string;
            label: string;
            description: string;
            requires_master_key: boolean;
            config_schema: components["schemas"]["IntegrationConfigFieldSchema"][];
        };
        IntegrationListItem: {
            /** Format: int64 */
            id: number;
            integration_type: string;
            provider: string;
            display_name: string;
            enabled: boolean;
            config: {
                [key: string]: unknown;
            };
            has_secrets: boolean;
            sort_order: number;
            created_at: string;
            updated_at: string;
        };
        IntegrationsListResponse: {
            items: components["schemas"]["IntegrationListItem"][];
        };
        IntegrationsCatalogResponse: {
            items: components["schemas"]["IntegrationCatalogEntry"][];
        };
        IntegrationCreateRequest: {
            provider: string;
            /** @enum {string} */
            type: "tag_source";
            display_name?: string;
            enabled?: boolean;
            config: {
                [key: string]: unknown;
            };
            secrets?: {
                [key: string]: unknown;
            };
        };
        IntegrationPatchRequest: {
            display_name?: string;
            enabled?: boolean;
            config?: {
                [key: string]: unknown;
            };
            secrets?: {
                [key: string]: unknown;
            };
        };
        IntegrationResponse: {
            item: components["schemas"]["IntegrationListItem"];
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication failed */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Qobuz credentials not configured */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Upstream Qobuz error */
        BadGateway: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Conflict with current state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getOpenApiSpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI 3.1 specification */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    getServerInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerInfoResponse"];
                };
            };
        };
    };
    getQobuzSyncLatest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest sync run or null if none */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QobuzSyncLatestResponse"];
                };
            };
        };
    };
    qobuzOAuthStart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorize URL and state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QobuzOAuthStartResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    qobuzOAuthCallback: {
        parameters: {
            query?: {
                /** @description Authorization code (Qobuz may send `code_autorisation` instead) */
                code?: string;
                /** @description Authorization code as returned by Qobuz sign-in redirect */
                code_autorisation?: string;
                /** @description CSRF state (embedded in redirect_url from oauth/start; optional if only one pending flow) */
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to settings with success query param */
            307: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getQobuzConnection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connection status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QobuzConnectionStatusResponse"];
                };
            };
        };
    };
    qobuzLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disconnected */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listQobuzAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QobuzAccountsListResponse"];
                };
            };
        };
    };
    qobuzTestLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QobuzTestLoginRequest"];
            };
        };
        responses: {
            /** @description Token is valid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QobuzTestLoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    qobuzSync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sync completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QobuzSyncResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listQobuzFavorites: {
        parameters: {
            query: {
                type: "album";
                limit?: number;
                sort?: "title" | "artist" | "in_library";
                order?: "asc" | "desc";
                cursor?: string;
                q?: string;
                in_library?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated favorites */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QobuzFavoritesListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    addQobuzFavorites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QobuzFavoritesMutateRequest"];
            };
        };
        responses: {
            /** @description Added */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["BadGateway"];
        };
    };
    removeQobuzFavorites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QobuzFavoritesMutateRequest"];
            };
        };
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["BadGateway"];
        };
    };
    listDownloads: {
        parameters: {
            query?: {
                status?: components["schemas"]["DownloadJobStatus"];
                limit?: number;
                sort?: "id" | "created_at" | "status";
                order?: "asc" | "desc";
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadJobListResponse"];
                };
            };
        };
    };
    createDownload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDownloadRequest"];
            };
        };
        responses: {
            /** @description Job queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateDownloadResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createDownloadByUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDownloadByUrlRequest"];
            };
        };
        responses: {
            /** @description Job queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateDownloadResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            502: components["responses"]["BadGateway"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    purgeFinishedDownloads: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Purge result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadPurgeResponse"];
                };
            };
        };
    };
    getDownload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadJob"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    cancelDownload: {
        parameters: {
            query?: {
                /** @description When set, delete the job row instead of cancelling. */
                purge?: "1" | "true";
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled or purged */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    startLibraryScan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scan accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryScanStartResponse"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    getLibraryScanLatest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest scan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryScanLatestResponse"];
                };
            };
        };
    };
    getLibraryScan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scan run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryScanRunSummary"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listLibraryAlbums: {
        parameters: {
            query?: {
                limit?: number;
                sort?: "title" | "artist" | "year";
                order?: "asc" | "desc";
                cursor?: string;
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Album list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryAlbumListResponse"];
                };
            };
        };
    };
    getLibraryAlbum: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Album detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryAlbumDetailResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getLibraryAlbumCover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cover image bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                    "image/webp": string;
                    "image/bmp": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    putLibraryAlbumCover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "image/jpeg": string;
                "image/png": string;
                "image/webp": string;
                "image/bmp": string;
            };
        };
        responses: {
            /** @description Cover saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumCoverUploadResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            /** @description Cover image exceeds size limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getLibraryTrack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Track detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryTrackDetailResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    patchLibraryTrackTags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryTrackTagsPatchRequest"];
            };
        };
        responses: {
            /** @description Updated track */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryTrackDetailResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    albumMetadataLookup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlbumMetadataLookupRequest"];
            };
        };
        responses: {
            /** @description Candidate list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumMetadataLookupResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            502: components["responses"]["BadGateway"];
        };
    };
    albumMetadataApply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlbumMetadataApplyRequest"];
            };
        };
        responses: {
            /** @description Apply result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumMetadataApplyResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            502: components["responses"]["BadGateway"];
        };
    };
    listIntegrations: {
        parameters: {
            query?: {
                type?: "tag_source";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Integration list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationsListResponse"];
                };
            };
        };
    };
    createIntegration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntegrationCreateRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    integrationsCatalog: {
        parameters: {
            query?: {
                type?: "tag_source";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalog entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationsCatalogResponse"];
                };
            };
        };
    };
    deleteIntegration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    patchIntegration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntegrationPatchRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    subscribeEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
}
